### ISSUE TITLE
deploy:web:disable error since v2.8.4

### ISSUE THREAD

**Issue by CharlyP** [everzet/capifony#578]
Hi,

I'm using Capifony and the underlying Capistrano maintenance system to enable and disable my application and since upgrade to capifony 2.8.4 version the following error occurs:
```
/home/[...]/.rvm/gems/ruby-2.1.5/gems/capifony-2.8.4/lib/symfony2/web.rb:55:in `initialize': No such file or directory @ rb_sysopen - /home/[...]/current/web/maintenance.html (Errno::ENOENT)
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capifony-2.8.4/lib/symfony2/web.rb:55:in `new'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capifony-2.8.4/lib/symfony2/web.rb:55:in `block (3 levels) in load'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:46:in `block in execute_requested_actions'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:45:in `each'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/cli/help.rb:19:in `execute_requested_actions_with_help'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:34:in `execute!'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:14:in `execute'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/bin/cap:4:in `<top (required)>'
        from /home/[...]/.rvm/gems/ruby-2.1.5/bin/cap:23:in `load'
        from /home/[...]/.rvm/gems/ruby-2.1.5/bin/cap:23:in `<main>'
        from /home/[...]/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /home/[...]/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>
```

I downgraded capifony and found that up to 2.8.3 it's working ;)

**Comment by WouterSioen** [comment]
Seems like this commit has caused this issue: https://github.com/everzet/capifony/commit/045e5996784f564c27ce722c53d3cad21bcbc1ca

Capifony tries to write the file locally, using a path on the server (which in most cases don't exist on your local computer). It should put the file on the server instead.

The `put result, "#{latest_release}/#{web_path}/#{maintenance_basename}.html", :mode => 0644` line should be put back to achieve this result.

**Comment by webdevilopers** [comment]
Has this fix been merged into *2.8.6*? Still having the issue there.
Tried to install *2.8.7* on Ubuntu but not available yet:
```
sudo gem install capifony -v 2.8.7
sudo gem install capifony-2.8.7
```

**Comment by WouterSioen** [comment]
Nope. I've created a pull request to fix this (https://github.com/everzet/capifony/pull/579) but there is no reaction yet.

**Comment by webdevilopers** [comment]
Thanks for the PR. So far I downgraded to *2.8.3* as recommended by @CharlyP .
